#src/main/resources/application.yaml

server:
  port: 8888
  tomcat:
    relaxed-query-chars=[]:

spring:
  application:
    name: HRHelper
  datasource:
    url: jdbc:mariadb://localhost:3306/HRHelperDB
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: false

logging:
  level:
    org.springframework.web: DEBUG
    org.ilvendev.profiles.controllers: DEBUG
    org.ilvendev.attendance.controllers: DEBUG
    org.ilvendev.leaves.controllers: DEBUG
    org.ilvendev.payroll.controllers: DEBUG

