#src/main/resources/application.yaml

server:
  port: 8888

spring:
  application:
    name: HRHelper
  datasource:
    url: jdbc:mariadb://localhost:3306/HRHelperDB
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  h2:
    console:
      enabled: false